#!/bin/bash

# Retrieve arguments
domain=$1
path=$2

sudo yunohost app checkurl $domain$path -a rspamdui
if [[ ! $? -eq 0 ]]; then
  exit 1
fi

# Configure Nginx and reload
# Removing trailing '/' in path to handle both subdir and subdomain installs.
sed -i "s@PATHTOCHANGE@${path%/}@g" ../conf/nginx.conf
sudo cp ../conf/nginx.conf /etc/nginx/conf.d/$domain.d/rspamdui.conf
sudo service nginx reload
